# Generated by Django 6.0.1 on 2026-01-31 20:56

import cloudinary.models
import cv.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursorealizado',
            name='certificado_pdf',
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='nombrecurso',
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='nombreinstitucion',
        ),
        migrations.RemoveField(
            model_name='cursorealizado',
            name='numerohoras',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='actividadesrealizadas',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fechafin',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fechainicio',
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='descripcioncurso',
            field=models.CharField(default='Pendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='emailempresapatrocinadora',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='entidadpatrocinadora',
            field=models.CharField(default='Pendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='fechafin',
            field=models.DateField(default=django.utils.timezone.now, validators=[cv.models.validar_fecha_no_futura]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='fechainicio',
            field=models.DateField(default=django.utils.timezone.now, validators=[cv.models.validar_fecha_no_futura]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='nombrecontactoauspicia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='nombrerecurso',
            field=models.CharField(default='Pendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='cursorealizado',
            name='totalhoras',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.CharField(default='Pendiente', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(default=django.utils.timezone.now, validators=[cv.models.validar_fecha_no_futura]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='descripcion_alternativa',
            field=models.TextField(blank=True, help_text='Se mostrará si no hay PDF', null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fechaproducto',
            field=models.DateField(validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fechareconocimiento',
            field=models.DateField(validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], default='Bueno', max_length=40),
        ),
    ]
