# Generated by Django 6.0.1 on 2026-01-31 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_cursorealizado_certificado_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconocimiento',
            name='descripcion_alternativa',
        ),
    ]
