# Generated by Django 6.0.1 on 2026-01-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_reconocimiento_descripcion_alternativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
