# Generated by Django 6.0.1 on 2026-01-31 21:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_datospersonales_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursorealizado',
            name='vista_previa_cur',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='vista_previa_titulo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='vista_previa_exp',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='vista_previa_reco',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
